const ErrorCodes = Object.freeze({
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    TOO_MANY_REQUEST: "TOO_MANY_REQUEST",
    MISSING_PARAMETERS: "MISSING_PARAMETERS",
    INVALID_PATH: "INVALID_PATH!",
    AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",
    INVALID_TOKEN: "INVALID_TOKEN",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    LOGIN_CREDENTIAL_ERROR: "LOGIN_CREDENTIAL_ERROR",
    WRONG_OLD_PASSWORD: "WRONG_OLD_PASSWORD",
    WRONG_SMS_CODE: "WRONG_SMS_CODE",
    WRONG_PASSWORD_DESIGN: "WRONG_PASSWORD_DESIGN",
    ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
    WRONG_PASSWORD: "WRONG_PASSWORD",
    ERR_UNHANDLED_REJECTION: "ERR_UNHANDLED_REJECTION",
    INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
});

export default ErrorCodes;
